# Representación  de eje/ángulo

In [1]:
from defs_robotica import *
import numpy as np

#### dado un vector k y un ángulo phi encontrar la matriz de rotación resultante

In [4]:
k = np.array([25,12.5,6.25])/(25**2 + 12.5**2 + 6.25**2)**.5

radianes_o_grados('radianes')

phi = np.pi/3
#-----------------------------------------
matriZ = R_K_phi(k, phi)
matriZ[abs(matriZ)<10**(-6)] = 0
print(matriZ)

[[ 0.88095238  0.00149395  0.47320257]
 [ 0.37945843  0.5952381  -0.7083099 ]
 [-0.28272638  0.80354799  0.52380952]]


#

#### dados los ángulos alpha betha y phi encontrar R

In [3]:
R_k = R_Alf_Bet(alpha=1, betha=1, phi=2)
R_k[abs(R_k)<10**(-6)] = 0
print(R_k)

[[-0.12342156 -0.0354029   0.99172262  0.        ]
 [ 0.9471881   0.29386382  0.12836963  0.        ]
 [-0.29597606  0.95519144 -0.00273593  0.        ]
 [ 0.          0.          0.          1.        ]]


#
#### dada una matriz encontrar phi y K

In [21]:
k, phi = K_phi_dada_R(sss.transpose())
#-----------------------------------------
print('k = kx, ky, kz')
print(k)
print(f'{np.rad2deg(phi)} grados')

k = kx, ky, kz
[0. 0. 0.]
179.97780943987684 grados


#
#### generacion de una matriz R1_0*Rz*R0_1

In [35]:
sss = np.array([
    [-0.710914, 0.454277, 0.536873, 0],
    [0.454277, -0.286136, 0.843658, 0], 
    [0.536873, 0.843658, -0.00294985, 0],
    [0, 0, 0, 1]
])

s = sss[:3,:3]
print(s)

radianes_o_grados('grados')
R = Ry(90)@Rz(45)
R[abs(R)<10**(-6)] = 0
#print(R)


[[-0.7109  0.4542  0.5368]
 [ 0.4542 -0.2861  0.8436]
 [ 0.5368  0.8436 -0.0029]]


In [47]:
a = np.arccos((np.trace(s) -1)/2)
print(f'angulo = {a} rad')
a = 1/(2*np.sin(a))
print(a)

angulo = 3.141205355252782 rad
1290.9944730426964


In [44]:
 0.454277-0.843658

-0.38938100000000003