# Cinematica inversa DH

In [1]:
from defs_robotica import *
import numpy as np

In [10]:
A1 =  DH(0, -np.pi/2,  10, 0)
A2 =  DH(1,  np.pi/2 ,  2, 0)
A3 =  DH(0,     0,   13, 0)
T03 = A2
np.set_printoptions(suppress=True, precision=4)
print(T03)

[[ 1.  0.  0.  1.]
 [ 0.  0. -1.  0.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  0.  1.]]
