# Cinematica directa DH

#### Los algulos a ingresar deben de estar en radianes
##### usar np.deg2rad()
##### https://profesores.utec.edu.pe/oramos/teaching/201/fund-robotica/lectures.html   recursos para robotica

In [14]:
from defs_robotica import *
import numpy as np

In [15]:
#T_s(b1, a2, a3, d6, ang)
b1 = 1
a2 = 1
a3 = 1
d6 = .1
ang= (1, 1, 1, 1, 1, 0.6,)

T = T_s(b1, a2, a3, d6, ang)
tt = T[5]
print(tt)

[[-0.86597699  0.50006315  0.0045499   0.06753648]
 [-0.06329519 -0.10057634 -0.99291395  0.00518183]
 [-0.49606206 -0.86012862  0.11874839  2.76264325]
 [ 0.          0.          0.          1.        ]]


# cinematica inversa

In [16]:
final = cin_inversa(b1, a2, a3, d6, tt)
print(final)

[[ 1.      1.      1.      1.      1.      0.6   ]
 [ 1.      2.     -1.      2.      1.      0.6   ]
 [-2.1416  1.      1.     -1.8584  2.1416 -2.5416]
 [-2.1416  2.     -1.     -0.8584  2.1416 -2.5416]
 [ 1.      1.      1.     -2.1416 -1.     -2.5416]
 [ 1.      2.     -1.     -1.1416 -1.     -2.5416]
 [-2.1416  1.      1.      1.2832 -2.1416  0.6   ]
 [-2.1416  2.     -1.      2.2832 -2.1416  0.6   ]]


In [17]:

T_sol = T_s(b1, a2, a3, d6, final[2])
jj = T_sol[5]
print(jj.round(3) == tt.round(3))
print(' ')
print(tt)
print(' ')

print(jj)

[[ True  True  True False]
 [ True  True  True False]
 [ True  True  True  True]
 [ True  True  True  True]]
 
[[-0.86597699  0.50006315  0.0045499   0.06753648]
 [-0.06329519 -0.10057634 -0.99291395  0.00518183]
 [-0.49606206 -0.86012862  0.11874839  2.76264325]
 [ 0.          0.          0.          1.        ]]
 
[[-0.86598307  0.50005261  0.0045504  -0.06662721]
 [-0.06329718 -0.10058168 -0.99291329 -0.20376406]
 [-0.4960512  -0.86013412  0.11875395  2.76264381]
 [ 0.          0.          0.          1.        ]]
